In [1]:
import numpy as np

In [2]:
students=np.array([
    "rahul",
    "KALPESH",
    "OM",
    "sneha",
    "ajay",
    "jay"])

students


array(['rahul', 'KALPESH', 'OM', 'sneha', 'ajay', 'jay'], dtype='<U7')

In [26]:
marks=np.array([
    [80,85,75,82,65],
    [98,88,90,98,82],
    [55,87,92,85,75],
    [88,55,87,95,75],
    [87,92,85,75,38],
    [92,85,75,78,76]
])
marks 

array([[80, 85, 75, 82, 65],
       [98, 88, 90, 98, 82],
       [55, 87, 92, 85, 75],
       [88, 55, 87, 95, 75],
       [87, 92, 85, 75, 38],
       [92, 85, 75, 78, 76]])

In [8]:
subject=np.array([
    "Python",
    "SQL",
    "Excel",
    "PowerBI",
    "Statistics"
])
subject   

array(['Python', 'SQL', 'Excel', 'PowerBI', 'Statistics'], dtype='<U10')

In [9]:
marks.ndim

2

In [10]:
marks.shape

(6, 5)

In [11]:
marks.size

30

In [12]:
marks.dtype

dtype('int64')

In [13]:
total=np.sum(marks,axis=1)

In [14]:
total

array([387, 456, 394, 400, 417, 406])

In [15]:
per=(total/500)*100
per

array([77.4, 91.2, 78.8, 80. , 83.4, 81.2])

In [16]:
avg=np.mean(marks,axis=1)

In [17]:
avg

array([77.4, 91.2, 78.8, 80. , 83.4, 81.2])

In [18]:
classavg=np.mean(marks)
classavg

np.float64(82.0)

In [19]:
subAvg=np.mean(marks,axis=0)
subAvg

array([83.33333333, 82.        , 84.        , 85.5       , 75.16666667])

In [20]:
classmax=np.max(marks)
classmax

np.int64(98)

In [21]:
classmin=np.min(marks)
classmin

np.int64(55)

In [23]:
topper_idx=np.argmax(total)
topper_idx

np.int64(1)

In [27]:
pass_fail=np.all(marks>=40,axis=1)
pass_fail

array([ True,  True,  True,  True, False,  True])